console.log("Olá mundo!");

let firstName = "André";
let lastName = "Carvalho";
const price = 30;
// price = 20;

console.log(firstName);
console.log(lastName);
console.log(price);

// Os tipos primitivos:
//let itemName = "Pen"; // String
//let itemPrice = 3; // Numero
//let itemAvaliable = true; // Boolean
//let itemColor = "red";
//let itemColor; // Undefined
itemName = null; // Vazio

let Pen = 
{

    itemName: "Pen",
    itemPrice: 3,
    itemAvaliable: true,
    itemColor: "Red"

}

console.log(Pen);


let friends = ["Marcos", "Silvia", "Elisa"]
friends[1] = "Junior"
console.log(friends)
